frr version 8.4_git
frr defaults traditional
hostname frr-alpine-ssh-1
no ipv6 forwarding
service integrated-vtysh-config
!
ip route 0.0.0.0/0 192.168.122.1
!
interface eth0
 ip address 192.168.122.4/24
exit
!
interface eth1
 ip address 192.168.1.4/24
exit
!
