## Last changed: 2026-10-03 15:30:45 UTC
version 23.2R1.15;
system {
    host-name Australia;
    root-authentication {
        encrypted-password "$6$cQqCddT1$DB1AVwBEJ4x79prjDAT0Viv1kyimY9hWqAP8y3JrhDp7EDRkTpjCFouZS7T0ALRG2nsJjLA5ln1zXI8jmdnvu0";
    }
    login {
        class SOLO-CONFIG {
            permissions view-configuration;
        }
        user victor {
            uid 2001;
            class SOLO-CONFIG;
            authentication {
                encrypted-password "$6$RsMZv.rJ$nYGb.EUtcCl0NYN.byxcG/dYqD9OhldjQ8wSuPIBv5JUHpgYaJZ84S1SWNQs4TOVkqM4ICkGOECtazKxjlnmv/";
            }
        }
    }
    services {
        ssh {
            sftp-server;
        }
        netconf {
            ssh;
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
    archival {
        configuration {
            transfer-on-commit;
            archive-sites {
                "scp://victor@192.168.122.6:/var/home/victor/config/" password "$9$QGEU3AuSyK8LNres4JZq.BIEyeWLxNVs28L";
            }
        }
    }
    processes {
        dhcp-service {
            traceoptions {
                file dhcp_logfile size 10m;
                level all;
                flag packet;
            }
        }
    }
}
security {
    ssh-known-hosts {
        host 192.168.122.6 {
            ecdsa-sha2-nistp256-key AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLsPgg/aMexwMsPkCpNaXSx7MmAFCvDMdgIbmg3N5VgF+dcwhKW+rVB6P2NPl50euhDOh63ERlnFZKPzSvxR0Jw=;
        }
    }
}
interfaces {
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.255.255.14/30;
            }
            family inet6 {
                address 2021:16:17:13::2/64;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 10.5.0.1/16;
            }
            family inet6 {
                address 2021:16:17:5::1/64;
                address 2021:16:17:5::2/64;
            }
        }
    }
    ge-0/0/9 {
        unit 0 {
            family inet {
                address 192.168.122.6/24;
            }
        }
    }
    fxp0 {
        unit 0 {
            family inet;
            family inet6 {
                dhcpv6-client {
                    client-type stateful;
                    client-ia-type ia-na;
                    client-identifier duid-type duid-ll;
                    vendor-id Juniper:vmx:VM6AB949BB9D;
                }
            }
        }
    }
}
routing-options {
    router-id 5.5.5.5;
}
protocols {
    router-advertisement {
        interface fxp0.0 {
            managed-configuration;
        }
        interface ge-0/0/2.0;
    }
    ospf {
        area 0.0.0.0 {
            interface ge-0/0/2.0;
            interface ge-0/0/1.0;
        }
    }
    ospf3 {
        area 0.0.0.0 {
            interface ge-0/0/2.0;
            interface ge-0/0/1.0;
        }
    }
}
